### ISSUE TITLE
Use RainLoop instead of Roundcube

### ISSUE THREAD

**Issue by bpeterman** [sovereign/sovereign#594] opened 2016-09-28 23:14 UTC
Has there been any thought put into using RainLoop over roundcube?  I'm using RainLoop locally and it seems pretty solid.  It probably wouldn't take me too long to add the setup to ansible.  The manual installation was pretty straight forward.

**Comment by neuhaus** [comment] 2016-09-29 15:59
There don't seem to be any packages yet for Rainloop, so what would be the advantages?

**Comment by wsteitz** [comment] 2016-10-09 09:26
I case we are rethinking the webmail client used in sovereign, [mailpile](https://www.mailpile.is/) looks very interesting.

**Comment by neuhaus** [comment] 2016-10-10 08:43
Looks nice. Again, what are the benefits to change from Roundcube to RainLoop or mailpile?

**Comment by bpeterman** [comment] 2016-10-10 22:59
Well, I think the main reason I switched to RainLoop was because Roundcube doesn't appear to be working currently with Sovereign (didn't work for me "out of the box").  Might just be personal preference as I feel the Roundcube interface is fairly antiquated.  Just thought I'd throw the idea out there to see what others think.

**Comment by mikeashley** [comment] 2016-10-10 23:29
Could you be more specific about what didn't work?  Fresh install of Debian 8?  Debian 7?

**Comment by bpeterman** [comment] 2016-10-11 17:20
I'm mainly referring to this.  https://github.com/sovereign/sovereign/commit/195d8811fc1551afbe84bb7b6267a25008653fe9#diff-04c6e90faac2675aa89e2176d2eec7d8R22  

I thought it was a known issue.  I can't recall the exact errors but it was a fresh install on Ubuntu 16.04.

**Comment by mikeashley** [comment] 2016-10-12 08:35
Ah, the README was out of date; I corrected it on master.  The master branch doesn't officially support Ubuntu yet but would love to see that regression fixed with a PR.  On the wheezy branch (which supports Trusty but not Xenial), Roundcube is indeed a little rough to install due to nagging issues with unattended installs of the package with the postgres backend.  It has to be patched up manually.

**Comment by neuhaus** [comment] 2017-02-06 13:05
Talking about the wheezy branch.. we should announce a date when we will stop supporting it.

**Comment by neuffer** [comment] 2017-02-06 17:23
On 06.02.2017 14:05, Sven Neuhaus wrote:

> woTalking about the wheezy branch.. we should announce a date when we
> will stop supporting it.
>

Also Debian 9 has just been frozen, so it would be prudent to start
thinking about compatibility to it.

**Comment by neuhaus** [comment] 2019-07-12 08:50
I'm closing this issue for now. If you can provide a pull request, please do. It should work with Debian 8-10 and Ubuntu 16.04 and Ubuntu 18.04.

**Closed by neuhaus** 2019-07-12 08:50 UTC
Labels: enhancement
