### ISSUE TITLE
Access forbidden for main webpage

### ISSUE THREAD

**Issue by Titan-C** [sovereign/sovereign#658] opened 2017-02-20 12:26 UTC
I noticed that after clearing all my cache and cookies and then I visit my domain say : `example.com` my browser will try to open the insecure `http://example.com` website. In this case I get the reply
```
Forbidden

You don't have permission to access / on this server.
Apache/2.4.10 (Debian) Server at example.com Port 80
```
The moment I try to go into `www.example.com` it will instantly refresh to the secure version of `https://example.com` and from then on the browser will always know to load the secure version of the website(until the next time I clear my cache) even if I just type `example.com`

**Comment by neuhaus** [comment] 2017-02-21 13:26
duplicate of issue #524

**Closed by neuhaus** 2017-02-21 13:26 UTC
