### ISSUE TITLE
GUI for managing mail virtual users and domains (after installation)

### ISSUE THREAD

**Issue by andysaini** [sovereign/sovereign#448] opened 2015-12-16 11:24 UTC
it has been brought to my attention that no such provision exists currently, is there a 3rd party package that can be incorporated?

**Comment by neuhaus** [comment] 2015-12-16 12:17
Duplicate of #447

**Comment by neuhaus** [comment] 2015-12-16 12:18
OK sorry it's you again, let's rephrase this issue to make it a feature request

**Comment by neuhaus** [comment] 2015-12-16 12:19
See also #418

**Comment by neuhaus** [comment] 2015-12-22 10:26
OK we have several choices here. We can point to some GUIs in the README. We can test some and point out potential problems. Or we can include a GUI. Opinions?

**Comment by andysaini** [comment] 2015-12-23 19:23
including a GUI would be awesome.

**Comment by lukecyca** [comment] 2015-12-23 20:19
I don't think this belongs in Sovereign.

A configuration GUI that runs on the server is antithetical to configuration management tools such as Ansible. We already have some components that require configuration through a GUI, and they just don't sit right in the setup procedure, requiring hand-wavy instructions and poor reproducibility if you have to reprovision your server..

**Comment by neuhaus** [comment] 2016-01-16 13:18
If you reprovision your server, won't restore it from backup (including DB backup)? We already provide a backup solution. If you use the back, the users would be preserved even if they were added after the initial installation.

**Comment by neuffer** [comment] 2016-01-24 08:44
I can recommend Postfixadmin as a powerful web and CLI based Postfix management tool.
http://sourceforge.net/projects/postfixadmin/
The project is active and close to its 3.0 release.
Even so the Debian maintainer keeps an ancient 2.3.7 in Debian, it is trivial to build a current Debian package from the sources since it already contains the necessary data.

Ansible and Postfixadmin are not antithetical as incorrectly claimed above, but in fact complement each other. One is for setting up and configuring the server, the other for the day to day usage and management of the mail service. For example: You wouldn't use Ansible to create your user account and projects on Github either or would you?  Instead you would use it to configure the Github servers and maybe the Github software on to of them.

**Comment by shaneonabike** [comment] 2016-04-16 12:12
@neuffer did you install that after you had built your server? Or are you just suggesting it. I had tried it before but never got it to mesh with an existing install :/

**Comment by neuffer** [comment] 2016-04-18 06:52
On 16. April 2016 14:13:00 MESZ, wrote Shane <notifications@github.com>:

    @neuffer <https://github.com/neuffer> did you install that after you
    had built your server? Or are you just suggesting it. I had tried it
    before but never got it to mesh with an existing install :/


Suggesting it, but for me postfix & postfixadmin together with
postgresql are a given and dovecot pretty much as well as this is my
current setup.

Whether I do my teck refresh "hand crafted" as before or use sovereign
or some other framework is up for discussion.

Cheers
  Mike

**Comment by shaneonabike** [comment] 2016-04-18 14:21
Mmmm ok. I had also come across this great tool VIMBadmin which also looks really promising but I am unsure as to whether I can install that with an existing one either *sigh*

**Comment by neuffer** [comment] 2016-04-18 18:46
On 18.04.2016 16:21, Shane wrote:
>
> Mmmm ok. I had also come across this great tool VIMBadmin which also
> looks really promising but I am unsure as to whether I can install
> that with an existing one either /sigh/
>

I am sure I am able to integrate postfixadmin with Sovereign once it is
set up with a current version of Debian testing.
I know next to nothing about Ansible and Python is definitely not my
language of choice but I think I'll manage.

My integration effort just might not be Sovereign compatible (i.e. no
yaml config / playbook or whatever). I don't know yet how many configs
I'll need to amend.
At the very least the postfix and Dovecot configs, some Postgresql,
possibly Roundcube,

I might out myself as dense and backward here, but I don't really see
what Ansible/Sovereign gives me beyond a one-off installation script.
While tracking Debian testing I'll always encounter config changes that
I'll need to resolve manually. How does Ansible/Sovereign help
me there? I'd REALLY appreciate some enlightenment here.

And yes, my private mail servers have been tracking Debian since
~0.93R6. First with what would later be called unstable,
then I switched to testing when testing was introduced in Debian. First
running sendmail, then since ~1999 postfix.
Sticking to the stable release was never my thing, at least not for my
private servers. :-)

**Comment by carljm** [comment] 2016-04-18 19:09
@neuffer The idea with Ansible is precisely that it is _not_ a one-time install tool, but the single source of truth for your server's configuration. All configuration changes are made via Ansible and are thus tracked in a VCS and fully reproducible. Ideally you should be able at any point to backup your data, destroy your server, create a brand-new server with the same OS, run Ansible against it, restore your data, and be right back in business.

Given that the whole point of Ansible is reproducible servers, it is more difficult when tracking an unstable underlying distribution target. You can certainly have an Ansible config targeting "the latest Debian testing", it just means that Ansible config is likely to need updating more frequently as changes are made in the underlying OS.

You should really never touch a configuration file manually/directly on a server managed by Ansible.

**Comment by mikeashley** [comment] 2016-05-21 10:29
This discussion seems to have run its course.  I am going to go ahead and close this issue.

**Closed by mikeashley** 2016-05-21 10:29 UTC
Labels: discussion, enhancement
